name: Android CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
          cache: gradle
      - name: grant execute permission for gradlew
        run: chmod +x gradlew
      - name: run Android Lint
        run: ./gradlew lintDebug
      - name: setup Detekt
        uses: peter-murray/setup-detekt@v2
        with:
          detekt_vision: 1.20
      - name: run Detekt
        run: detekt-cli --version
      - name: upload Android Lint results
        uses: actions/upload-artifact@v2
        with:
          name: Android Lint
          path: app/build/reports/lint-results.html
        continue-on-error: false

